# Generated by Django 3.0.2 on 2020-01-10 14:45

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('profile_pic', models.ImageField(upload_to='profile_images/')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('description', models.TextField(max_length=500)),
                ('posted', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
