# Generated by Django 3.0.2 on 2020-01-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('Profile_pic', models.ImageField(upload_to='profile_images/')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
