# Generated by Django 3.0.2 on 2020-01-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratess', '0003_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
